### ISSUE TITLE
Allow widget selectors to be styled independently of buttons.

### ISSUE THREAD

**Issue by leniency** [telerik/kendo-theme-bootstrap#336]
Currently the input widget selectors (combobox, date/time pickers, the entire dropdownlist) take the same coloring as secondary buttons.

Can the widget selectors be setup to be styled independently. They can still default to the button colors, but allow a way to change them without changing the buttons.

For example, if the secondary bootstrap color is a dark grey, the entire dropdownlist box is also a dark grey and stands out greatly from the default bootstrap select lists. Or the date picker - the selector stands out a lot - would be nice to tone that down without impacting other styles.

**Comment by joneff** [comment]
To overcome this behaviour, we've introduced a new file [_bootstrap-overrides.scss](https://github.com/telerik/kendo-theme-bootstrap/blob/94d8fe024a1e36222be66ec627a816f39b7eb46c/scss/_bootstrap-overrides.scss), which, as the name suggests, overrides some of the values, including the said `$secondary` variable. We then go on to plug some variables need for [Sass Themebuilder](http://themebuilder.telerik.com) customization, while respecting values set by developers thanks to `!default` flag

https://github.com/telerik/kendo-theme-bootstrap/blob/94d8fe024a1e36222be66ec627a816f39b7eb46c/scss/_bootstrap-overrides.scss#L18-L34

**Comment by leniency** [comment]
Sorry, this doesn't address the core issue at all.

Here's the contents of dropdownlist/_theme.scss:

```scss
@include exports("dropdownlist/theme") {
    // Dropdown
    .k-dropdown {
        .k-dropdown-wrap {
            @include appearance( button );
            transition: $transition;
        }

        // Hover state
        > :hover,
        .k-state-hover { @include appearance( hovered-button ); }

        // Focused state
        .k-state-focused {
            box-shadow: $button-focused-shadow;
        }

        // Active state
        .k-state-active {
            @include appearance( pressed-button );
        }
    }
}
```

It uses the button mixins for coloring the dropdown toggle. This means that whatever color I set the buttons, it the dropdown toggle ends up the same - and I would rather style them separately.  Ie, i like the colored buttons but would prefer a white or transparent toggle. Same with the calendar control.
