### ISSUE TITLE
Inconsistent header font size in DateInputs

### ISSUE THREAD

**Issue by lkarakoleva** [telerik/kendo-theme-bootstrap#350]
Calendar's and TimePicker's headers should have consistent font size and color:
```css
.k-calendar th {
...
    font-size: $font-size-sm;
...
}
```
`header color: $header-text`
